# Generated by Django 3.2.13 on 2022-06-12 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20190129_2304'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name='Constance',
                ),
            ],
        ),
    ]
